# Nombre del archivo de salida
OUTPUT = servidor

# Compilador a usar
CC = g++

# Flags del compilador
CFLAGS = -std=c++11 -pthread

# Archivos fuente
SOURCES = servidor\ 2.0.cpp

all:
    $(CC) $(CFLAGS) $(SOURCES) -o $(OUTPUT)

clean:
    rm -f $(OUTPUT)